-- ============================================================================
-- GbanaB2B · Migration 0008 · products.slug default
-- The slug is always generated by products_guard(); clients are not granted
-- the column. A default lets inserts omit it cleanly.
-- ============================================================================
alter table public.products alter column slug set default 'pending';
